### ISSUE TITLE
Does this library support installation of chrome extension?

### ISSUE THREAD

**Issue by Ajeey** [jamesmortensen/node-webkit-chrome-api-stubs#4]
Hi wanted to check if this library supports installation of chrome extensions for my node webkit app?

**Comment by jamesmortensen** [comment]
@Ajeey sorry for the really late reply on this.  This library just stubs out some of the APIs so that a Chrome App that's moved to a node-webkit app will not fail to run.  

I haven't been following what's happening with node-webkit, whether or not they support chrome-extensions or not, but I think if all of the same API's are implemented here, a chrome-extension could theoretically be plugged into node-webkit.  

One challenge is Chrome Apps no longer exist, making this library obsolete, but I'm guessing the techniques used here could potentially be used to make some extensions run with node-webkit.  Hope this helps!
